services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./database/03_views.sql:/docker-entrypoint-initdb.d/03_views.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "41286:80" # mi carnet para acceder a la app (241286) al ser un numero tan alto el 2 se omite para evitar problemas 
    depends_on:
      - backend

volumes:
  postgres_data: