// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/auth/login').default>>>>
    }
    '/api/categorias/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/categorias/[id]').default>>>>
    }
    '/api/categorias': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/categorias/index').default>>>>
    }
    '/api/clientes/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/clientes/[id]').default>>>>
    }
    '/api/clientes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/clientes/index').default>>>>
    }
    '/api/empleados/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/empleados/[id]').default>>>>
    }
    '/api/empleados': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/empleados/index').default>>>>
    }
    '/api/productos/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/productos/[id]').default>>>>
    }
    '/api/productos': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/productos/index').default>>>>
    }
    '/api/proveedores/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/proveedores/[id]').default>>>>
    }
    '/api/proveedores': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/proveedores/index').default>>>>
    }
    '/api/reportes/clientes-sin-compra': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/reportes/clientes-sin-compra').default>>>>
    }
    '/api/reportes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/reportes/index').default>>>>
    }
    '/api/reportes/stock-bajo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/reportes/stock-bajo').default>>>>
    }
    '/api/reportes/top-clientes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/reportes/top-clientes').default>>>>
    }
    '/api/reportes/ventas-por-categoria': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/reportes/ventas-por-categoria').default>>>>
    }
    '/api/ventas/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/ventas/[id]').default>>>>
    }
    '/api/ventas': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/ventas/index').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index').default>>>>
    }
  }
}
export {}